import { jsPDF } from 'jspdf'
import { format } from 'date-fns'

export function usePdfExport() {
  /**
   * Generate a medical history PDF for a pet
   * @param {Object} pet - Pet object with name, emoji, species
   * @param {Array} activities - All activities for the pet
   * @param {Object} household - Household info
   */
  function generateMedicalPdf(pet, activities, household) {
    try {
      // Create new PDF (portrait, mm, A4)
      const doc = new jsPDF('p', 'mm', 'a4')
      const pageWidth = doc.internal.pageSize.getWidth()
      const pageHeight = doc.internal.pageSize.getHeight()
      const margin = 20
      const contentWidth = pageWidth - (margin * 2)
      let yPos = margin

      // Helper function to check if new page is needed
      const checkNewPage = (neededHeight) => {
        if (yPos + neededHeight > pageHeight - margin) {
          doc.addPage()
          yPos = margin
          return true
        }
        return false
      }

      // Helper function to add footer
      const addFooter = () => {
        const pageNum = doc.internal.getCurrentPageInfo().pageNumber
        doc.setFontSize(8)
        doc.setTextColor(150)
        doc.text(
          `Generated by Tailr - Page ${pageNum}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        )
        doc.text(
          format(new Date(), 'MMM d, yyyy'),
          pageWidth - margin,
          pageHeight - 10,
          { align: 'right' }
        )
      }

      // ===== HEADER =====
      doc.setFillColor(16, 185, 129) // Sage green
      doc.rect(0, 0, pageWidth, 40, 'F')

      doc.setFontSize(24)
      doc.setTextColor(255, 255, 255)
      doc.text('🐾 Tailr', margin, yPos + 10)

      doc.setFontSize(14)
      doc.text('Medical History Report', margin, yPos + 20)

      yPos = 50

      // ===== PET INFO =====
      doc.setFontSize(16)
      doc.setTextColor(17, 24, 39)
      doc.text(`${pet.emoji} ${pet.name}`, margin, yPos)
      yPos += 8

      doc.setFontSize(10)
      doc.setTextColor(100)
      doc.text(`Species: ${pet.species || 'Unknown'}`, margin, yPos)
      yPos += 5
      if (pet.breed) {
        doc.text(`Breed: ${pet.breed}`, margin, yPos)
        yPos += 5
      }
      doc.text(`Household: ${household.memberName || 'Unknown'}`, margin, yPos)
      yPos += 5
      doc.text(`Report Date: ${format(new Date(), 'MMMM d, yyyy')}`, margin, yPos)
      yPos += 12

      // Separator line
      doc.setDrawColor(200)
      doc.line(margin, yPos, pageWidth - margin, yPos)
      yPos += 10

      // Filter medical activities
      const vetVisits = activities.filter(a => a.type === 'Vet Visit').sort((a, b) => b.timestamp - a.timestamp)
      const vaccinations = activities.filter(a => a.type === 'Vaccination').sort((a, b) => b.timestamp - a.timestamp)
      const weightChecks = activities.filter(a => a.type === 'Weight Check').sort((a, b) => b.timestamp - a.timestamp)

      // ===== VET VISITS SECTION =====
      if (vetVisits.length > 0) {
        checkNewPage(20)
        doc.setFontSize(14)
        doc.setTextColor(17, 24, 39)
        doc.text('🏥 Vet Visits', margin, yPos)
        yPos += 8

        vetVisits.forEach((visit, index) => {
          const boxHeight = 20 + (visit.medicalData?.notes ? 10 : 0)
          checkNewPage(boxHeight + 5)

          // Box for each visit
          doc.setFillColor(249, 250, 251)
          doc.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, 'F')

          doc.setFontSize(10)
          doc.setTextColor(17, 24, 39)
          doc.setFont(undefined, 'bold')
          doc.text(
            format(visit.timestamp, 'MMM d, yyyy'),
            margin + 5,
            yPos + 6
          )

          doc.setFont(undefined, 'normal')
          doc.setTextColor(100)

          if (visit.medicalData?.cost) {
            doc.text(
              `Cost: $${visit.medicalData.cost.toFixed(2)}`,
              pageWidth - margin - 5,
              yPos + 6,
              { align: 'right' }
            )
          }

          if (visit.medicalData?.notes) {
            const lines = doc.splitTextToSize(visit.medicalData.notes, contentWidth - 15)
            doc.text(lines, margin + 5, yPos + 12)
          }

          yPos += boxHeight + 5
        })

        yPos += 5
      }

      // ===== VACCINATIONS SECTION =====
      if (vaccinations.length > 0) {
        checkNewPage(20)
        doc.setFontSize(14)
        doc.setTextColor(17, 24, 39)
        doc.text('💉 Vaccinations', margin, yPos)
        yPos += 8

        vaccinations.forEach((vacc, index) => {
          const boxHeight = 20 + (vacc.medicalData?.notes ? 10 : 0)
          checkNewPage(boxHeight + 5)

          doc.setFillColor(249, 250, 251)
          doc.roundedRect(margin, yPos, contentWidth, boxHeight, 3, 3, 'F')

          doc.setFontSize(10)
          doc.setTextColor(17, 24, 39)
          doc.setFont(undefined, 'bold')
          doc.text(
            vacc.medicalData?.vaccineName || 'Unknown Vaccine',
            margin + 5,
            yPos + 6
          )

          doc.setFont(undefined, 'normal')
          doc.setTextColor(100)
          doc.text(
            format(vacc.timestamp, 'MMM d, yyyy'),
            pageWidth - margin - 5,
            yPos + 6,
            { align: 'right' }
          )

          if (vacc.medicalData?.notes) {
            const lines = doc.splitTextToSize(vacc.medicalData.notes, contentWidth - 15)
            doc.text(lines, margin + 5, yPos + 12)
          }

          yPos += boxHeight + 5
        })

        yPos += 5
      }

      // ===== WEIGHT HISTORY SECTION =====
      if (weightChecks.length > 0) {
        checkNewPage(20)
        doc.setFontSize(14)
        doc.setTextColor(17, 24, 39)
        doc.text('⚖️ Weight History', margin, yPos)
        yPos += 8

        // Table header
        doc.setFillColor(243, 244, 246)
        doc.rect(margin, yPos, contentWidth, 8, 'F')
        doc.setFontSize(9)
        doc.setFont(undefined, 'bold')
        doc.setTextColor(17, 24, 39)
        doc.text('Date', margin + 3, yPos + 5)
        doc.text('Weight', margin + 35, yPos + 5)
        doc.text('Notes', margin + 60, yPos + 5)
        yPos += 8

        // Table rows
        doc.setFont(undefined, 'normal')
        weightChecks.forEach((weight, index) => {
          checkNewPage(8)

          if (index % 2 === 0) {
            doc.setFillColor(249, 250, 251)
            doc.rect(margin, yPos, contentWidth, 7, 'F')
          }

          doc.setFontSize(9)
          doc.setTextColor(60)
          doc.text(
            format(weight.timestamp, 'MMM d, yyyy'),
            margin + 3,
            yPos + 5
          )

          const weightValue = weight.medicalData?.weight || '?'
          const weightUnit = weight.medicalData?.unit || 'lbs'
          doc.text(
            `${weightValue} ${weightUnit}`,
            margin + 35,
            yPos + 5
          )

          if (weight.medicalData?.notes) {
            const notes = doc.splitTextToSize(
              weight.medicalData.notes,
              contentWidth - 65
            )
            doc.text(notes[0], margin + 60, yPos + 5) // Only first line in table
          }

          yPos += 7
        })

        yPos += 5
      }

      // ===== SUMMARY SECTION =====
      checkNewPage(30)
      doc.setDrawColor(200)
      doc.line(margin, yPos, pageWidth - margin, yPos)
      yPos += 8

      doc.setFontSize(12)
      doc.setTextColor(17, 24, 39)
      doc.text('Summary', margin, yPos)
      yPos += 8

      doc.setFontSize(10)
      doc.setTextColor(100)
      doc.text(`Total Vet Visits: ${vetVisits.length}`, margin, yPos)
      yPos += 6
      doc.text(`Total Vaccinations: ${vaccinations.length}`, margin, yPos)
      yPos += 6
      doc.text(`Weight Checks: ${weightChecks.length}`, margin, yPos)
      yPos += 6

      if (weightChecks.length >= 2) {
        const firstWeight = weightChecks[weightChecks.length - 1]
        const lastWeight = weightChecks[0]

        // Convert to lbs for comparison
        const firstLbs = firstWeight.medicalData.unit === 'kg'
          ? firstWeight.medicalData.weight * 2.20462
          : firstWeight.medicalData.weight

        const lastLbs = lastWeight.medicalData.unit === 'kg'
          ? lastWeight.medicalData.weight * 2.20462
          : lastWeight.medicalData.weight

        const change = (lastLbs - firstLbs).toFixed(1)
        const direction = change > 0 ? 'gained' : 'lost'

        doc.text(
          `Weight Change: ${direction} ${Math.abs(change)} lbs since ${format(firstWeight.timestamp, 'MMM d, yyyy')}`,
          margin,
          yPos
        )
      }

      // Add footer to all pages
      const totalPages = doc.internal.getNumberOfPages()
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i)
        addFooter()
      }

      // Generate filename
      const filename = `${pet.name}_Medical_History_${format(new Date(), 'yyyy-MM-dd')}.pdf`

      // Save PDF
      doc.save(filename)

      return { success: true, filename }
    } catch (error) {
      console.error('PDF generation error:', error)
      return { success: false, error: error.message }
    }
  }

  /**
   * Generate a quick medical summary (one-pager)
   * @param {Object} pet - Pet object
   * @param {Array} activities - Recent activities
   */
  function generateQuickSummary(pet, activities) {
    try {
      const doc = new jsPDF('p', 'mm', 'a4')
      const pageWidth = doc.internal.pageSize.getWidth()
      const margin = 20
      let yPos = margin

      // Header
      doc.setFillColor(16, 185, 129)
      doc.rect(0, 0, pageWidth, 35, 'F')

      doc.setFontSize(20)
      doc.setTextColor(255, 255, 255)
      doc.text(`${pet.emoji} ${pet.name}`, margin, yPos + 8)

      doc.setFontSize(12)
      doc.text('Quick Medical Summary', margin, yPos + 16)

      yPos = 45

      // Get latest records
      const latestVet = activities.find(a => a.type === 'Vet Visit')
      const latestVacc = activities.find(a => a.type === 'Vaccination')
      const latestWeight = activities.find(a => a.type === 'Weight Check')

      doc.setFontSize(11)
      doc.setTextColor(17, 24, 39)

      if (latestVet) {
        doc.setFont(undefined, 'bold')
        doc.text('Last Vet Visit:', margin, yPos)
        doc.setFont(undefined, 'normal')
        doc.text(format(latestVet.timestamp, 'MMMM d, yyyy'), margin + 35, yPos)
        yPos += 8
      }

      if (latestVacc) {
        doc.setFont(undefined, 'bold')
        doc.text('Last Vaccination:', margin, yPos)
        doc.setFont(undefined, 'normal')
        doc.text(
          `${latestVacc.medicalData?.vaccineName || 'Unknown'} - ${format(latestVacc.timestamp, 'MMM d, yyyy')}`,
          margin + 35,
          yPos
        )
        yPos += 8
      }

      if (latestWeight) {
        doc.setFont(undefined, 'bold')
        doc.text('Current Weight:', margin, yPos)
        doc.setFont(undefined, 'normal')
        doc.text(
          `${latestWeight.medicalData?.weight} ${latestWeight.medicalData?.unit || 'lbs'}`,
          margin + 35,
          yPos
        )
      }

      const filename = `${pet.name}_Summary_${format(new Date(), 'yyyy-MM-dd')}.pdf`
      doc.save(filename)

      return { success: true, filename }
    } catch (error) {
      console.error('PDF generation error:', error)
      return { success: false, error: error.message }
    }
  }

  return {
    generateMedicalPdf,
    generateQuickSummary
  }
}
